<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="stand_wid" 
        value="0.03" />
    <xacro:property name="stand_len"
        value="0.03" />
    <xacro:property name="stand_hgt"
        value="0.06" />

    <xacro:property name="camera_wid" 
        value="0.02" />
    <xacro:property name="camera_len"
        value="0.005" />
    <xacro:property name="camera_hgt"
        value="0.02" />



    <link name="camera_stand_link">
        <visual>
            <geometry>
                <box size="${stand_len} ${stand_wid} ${stand_hgt}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${stand_len} ${stand_wid} ${stand_hgt}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="0.02" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="${(1.0/12.0)*((stand_len * stand_len) + (stand_hgt * stand_hgt))}" 
                     iyy="${(1.0/12.0)*((stand_wid * stand_wid) + (stand_hgt * stand_hgt))}" 
                     izz="${(1.0/12.0)*((stand_wid * stand_wid) + (stand_len * stand_len))}" 
                     ixy="0.0" ixz="0.0" iyz="0.0" 
                     />
        </inertial>
    </link>

    <joint name="base_camera_stand_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_stand_link" />
        <origin xyz="${box_len/6.0} 0 ${box_hgt/2.0}" rpy="0 0 0" />
    </joint>


    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_len} ${camera_wid} ${camera_hgt}" />
            </geometry>
            <origin xyz="${camera_len/2.0} 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_len} ${camera_wid} ${camera_hgt}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="${(1.0/12.0)*((camera_len * camera_len) + (camera_hgt * camera_hgt))}" 
                     iyy="${(1.0/12.0)*((camera_wid * camera_wid) + (camera_hgt * camera_hgt))}" 
                     izz="${(1.0/12.0)*((camera_wid * camera_wid) + (camera_len * camera_len))}" 
                     ixy="0.0" ixz="0.0" iyz="0.0" 
                     />
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="camera_stand_link" />
        <child link="camera_link" />
        <origin xyz="${stand_wid/2.0} 0 ${stand_hgt/2.0}" rpy="0 0 0" />
    </joint>


    <link name="camera_link_optical">
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link" />
        <child link="camera_link_optical" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    </joint>

</robot>