<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="laser_frame">
        <visual>
            <geometry>
                <box size="0.04 0.04 0.025" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="0.04 0.04 0.025" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="0.01" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="${(1.0/12.0)*((0.04 * 0.04) + (0.025 * 0.025))}" 
                     iyy="${(1.0/12.0)*((0.04 * 0.04) + (0.025 * 0.025))}" 
                     izz="${(1.0/12.0)*((0.04 * 0.04) + (0.04 * 0.04))}" 
                     ixy="0.0" ixz="0.0" iyz="0.0" 
                     />
        </inertial>
    </link>


    <joint name="base_laser_joint" type="fixed">
        <parent link="base_link" />
        <child link="laser_frame" />
        <origin xyz="${box_len/6.0} 0 ${box_hgt/2.0}" rpy="0 0 0" />
    </joint>
</robot>